name: Swiftlint

on:
  pull_request:
    branches: [ main ]
    # .swiftファイルが変更にない場合は実行しない
    paths:
      - '**.swift'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Danger
        uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.12.3
        with:
            args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
