  name: Update Homebrew formula

  on:
    release:
      types:
        - released
  
  jobs:
    formula:
      name: Run update action
      runs-on: ubuntu-latest
      steps:
        - uses: mislav/bump-homebrew-formula-action@v1
          with:
            formula-name: hondana
            formula-path: hondana.rb
            homebrew-tap: KS1019/homebrew-formulae
          env:
            COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
